### ISSUE TITLE
Layertree desktop

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1708]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop

**Comment by eleu** [comment]
timeslider **and** datepicker need to be implemented.

**Comment by sbrunner** [comment]
what's different with:
WMS-time curseur / WMS-time date picker
?

**Comment by eleu** [comment]
timeslider / time curseur:
![image](https://cloud.githubusercontent.com/assets/1632411/12844933/c417259e-cc02-11e5-951a-a41573566e76.png)


datepicker:
![image](https://cloud.githubusercontent.com/assets/1632411/12844919/b34139e4-cc02-11e5-9ae5-b63ec20492f5.png)

**Comment by sbrunner** [comment]
Then it's the same ...

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by rbovard** [comment]
Thanks a lot for the work! Here are my remarks/questions.

### General
* There is no more an icon per layer (as now in 1.6)?

### Layer group
* How to see if a group is active/inactive?
* How to set visibilty of a group?
* How to expend/collapse a group?

### Loading
* How can we choose where the loading icon is shown? (I thougt a group was a WMS query)

### Reording
* I can see it in mookup but it would be nice to specify that the cursor change on header hover

### Extra action
* Metadata need also to be on a group (as now in 1.6)
* Zoom to will be visible only if out of scale?
* Opacity will be visible for all kind of layers?

**Comment by mriedo** [comment]
Thanks for the proposal. It looks very good to me.

I share some of Rémi's questions

I wonder why : for the group, the action button is visible and for leaf nodes, the actions button is displayed only on hover ? Will it be easy for users to find these options for layers ?

**Comment by svavoi** [comment]
+1 for questions and remarks from @rbovard 

Additional remarks and questions from us:

**Not selected & not visible at current scale**
- If layer is not selected it is confusing to have a tick. We think it is better to show no sign at all.
- If the layer is not visible at current scale it would be nice to have the zoom sign directly in front of the layer name and you can click there to zoom in.

Here a example of what I mean: 
![layertree_idea](https://cloud.githubusercontent.com/assets/5998978/13953154/c2ae28e0-f03a-11e5-9360-80d7452ddf56.png)

The layer icons are very important to us. We have many layer where the legend icon is directly displayed in the layer tree.

**Extra actions**
- We think two clicks to close a layer is too much.
- For non flush mode it is important to have a possibility to close all currently available layers.

**Time data**
- Time data symbol might be not clear to all users. It should be as big as the additional action symbol and on hover display a popover with an information text.

**Architecture**
- We prefer Popover

**Comment by ybolognini** [comment]
Here are answers to @rbovard. We'll come back for the rest.

@rbovard There is no more an icon per layer (as now in 1.6)?

There should be. @pgiraud will add the icon in at least one mockup.

@rbovard How to see if a group is active/inactive?

It is already working in the mobile layertree (see demo): if the group is inactive, its title/icon is grayed as well as all the layers in the group.

@rbovard How to set visibilty of a group?

By clicking on group's "state" icon or on group's title.

@rbovard How to expend/collapse a group?

By clicking on the first icon "arrow". @pgiraud please a a quick note about this in the specifications.

@rbovard How can we choose where the loading icon is shown? (I thougt a group was a WMS query)

No sure we understand the question. Why would one want to choose where the loading icon is shown? 

@rbovard Reordering. I can see it in mookup but it would be nice to specify that the cursor change on header hover

OK. @pgiraud please add a text to describe that the cursor changes on hover.

@rbovard Metadata need also to be on a group (as now in 1.6)

OK. @pgiraud please add a list of possible actions for the groups.

@rbovard Zoom to will be visible only if out of scale?

Yes. Same as 1.6.

@rbovard Opacity will be visible for all kind of layers?

Same as 1.6: opacity available for nodes linked to OL3 layer. Can be groups or layers.

**Comment by rbovard** [comment]
Thanks @ybolognini for your answers.

> There is no more an icon per layer (as now in 1.6)?
> - There should be. @pgiraud will add the icon in at least one mockup.

OK

> How to see if a group is active/inactive?
> - It is already working in the mobile layertree (see demo): if the group is inactive, its title/icon is grayed as well as all the layers in the group.

OK

> How to set visibilty of a group?
> - By clicking on group's "state" icon or on group's title.

OK, are you sure that's enough explicit for users (on layers there is a tick)?

> How to expend/collapse a group?
> - By clicking on the first icon "arrow". @pgiraud please a a quick note about this in the specifications.

OK

> How can we choose where the loading icon is shown? (I thougt a group was a WMS query)
> - No sure we understand the question. Why would one want to choose where the loading icon is shown?

My question was about the sentence "Can be either at the group or leaf level." For what I know a group is a WMS query, so the loading status can be only on group, no?

> Reordering. I can see it in mookup but it would be nice to specify that the cursor change on header hover
> - OK. @pgiraud please add a text to describe that the cursor changes on hover.

OK

> Metadata need also to be on a group (as now in 1.6)
> - OK. @pgiraud please add a list of possible actions for the groups.

OK

> Zoom to will be visible only if out of scale?
> - Yes. Same as 1.6.

OK

> Opacity will be visible for all kind of layers?
> - Same as 1.6: opacity available for nodes linked to OL3 layer. Can be groups or layers.

OK

**Comment by pgiraud** [comment]
Crap. I've edited @rbovard's comment instead of answering. Sorry.

**Comment by pgiraud** [comment]
@rbovard wrote: 

> My question was about the sentence "Can be either at the group or leaf level." For what I know a group is a WMS query, so the loading status can be only on group, no?

There may be cases where the leaf nodes correspond to OpenLayers layers. This is the case when WMTS layers are used. See http://sitn.ne.ch/theme/main.
Even in this case, you are right, the loading icon appears at the group level.
Should we keep this behavior in 2.x or can we display a loading icon at the leaf level when relevant?

**Comment by rbovard** [comment]
For me it's fine like it's now in 1.6...

**Comment by ybolognini** [comment]
+1 @rbovard 

If there's no other remarks, we'll keep it only on group level and @pgiraud will change the specs

**Comment by ybolognini** [comment]
@mriedo I wonder why : for the group, the action button is visible and for leaf nodes, the actions button is displayed only on hover ? Will it be easy for users to find these options for layers ?

The idea was to keep the tree "light" and not have this icon on every lines. But we can also display the icon on hover for the group. If there's no other remarks, we'll do it that way and @pgiraud will change the specs

@svavoi If layer is not selected it is confusing to have a tick. We think it is better to show no sign at all.

This was decided quite a long time ago. I suggest we continue like designed and see if this causes problems to users.

@svavoi If the layer is not visible at current scale it would be nice to have the zoom sign directly in front of the layer name and you can click there to zoom in.

Problem is: if we change this icon we don't know if layer is active or not (it could be active but not visible due to scale). And we think it's good to keep actions in the menu and limit to the maximum the number of buttons on the layer line.

@svavoi We think two clicks to close a layer is too much.

What do others think, is close button much used?  What we can do is to keep the action in the menu and add later an option to add a "trashcan" next to the wheel button.

@svavoi For non flush mode it is important to have a possibility to close all currently available layers.

This feature isn't planned for the 2.1, it will be designed later.

@svavoi Time data symbol might be not clear to all users. It should be as big as the additional action symbol and on hover display a popover with an information text.

We can add a tooltip on hover, yes. But otherwise we think it's quite clear.

**Comment by svavoi** [comment]
@ybolognini Thanks for your answers.

We use the close button much because we don’t work with the flush mode. It happens quite quickly that there are too many groups in the layertree and you want to get rid of some. I think it would really be a change for the worse to have it hidden two clicks away (especially if you work with non-flush mode). Why not have it on hover?

**Comment by pgiraud** [comment]
With more thinking, I changed my mind on several things.

 - I removed color on "state" icons so that user doesn't get distracted. The only elements that can be colorized are the legend items.
 - I removed the "check" (tick) element. The selected/unselected information is already given by the opacity of the text and legend icon. The tick image should only be used when there's no legend icon available (See PFP 4 in mockups).
 - Not visible at current scale is now managed by a clickable magnifier icon.

Please review the updated mockups.
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by gnerred** [comment]
What's visually the difference between a layer that is not checked and a layer that is not visible at current scale ?

**Comment by pgiraud** [comment]
@gnerred The magnifier icon.
In the mockups, the layer "Etat de la mensuration officielle" is selected but not visible at current scale.

**Comment by gnerred** [comment]
This icon is only visible on hover. With your proposal, when the user looks at the layertree, he is not able to see which layer is visible on map and which layer not. I think we loose something compared to 1.6... Any other opinion ?

**Comment by rbovard** [comment]
+1 @gnerred For me if the text is not grayed, the layer should be active (like it's now on 1.6)

@pgiraud Are you sure it's the best way to remove the thick? The current situation is not bad for me, what are your arguments to change the current behaviour?

**Comment by pgiraud** [comment]
> This icon is only visible on hover.

Nope. It's available any time. Not only on hover.

**Comment by pgiraud** [comment]
> Are you sure it's the best way to remove the thick? The current situation is not bad for me, what are your arguments to change the current behaviour?

In my previous mockups (and in the current 2.0), the "tick" was giving information on whether the layer is selected or not. This is redundant with the text and icon being black or grayed out.

But better than long explanation, see the following prototype. The OSM scale layer in the OSM function group can be out of scale.
https://pgiraud.github.io/ngeo/tree_indeterminate_3/examples/contribs/gmf/apps/desktop/

**Comment by gnerred** [comment]
We had a discussion with @svavoi and @rbovard and we are ok with your proposal, with following modifications : 

- when layer is not visible at current scale and not activated : layer is grey, with no icon. If the user activates it, the layer remains grey, but the magnifier appears. 

is it clear for you @pgiraud ? Any other opinion ?

**Comment by gnerred** [comment]
+1 @svavoi , i think fonctions on layergroup and layers should appear on hover, to avoid one more click, like it is on 1.6

**Comment by pgiraud** [comment]
> when layer is not visible at current scale and not activated : layer is grey, with no icon. If the user activates it, the layer remains grey, but the magnifier appears.

This unfortunately leads to confusion. It's then difficult to know if a layer is active (selected) or not.
I'd rather keep the grey color (lower opacity) for selection.

Here's an other option: using italic.
![screenshot from 2016-03-30 17 34 36](https://cloud.githubusercontent.com/assets/319774/14148114/89b4f9fa-f69e-11e5-891c-05b40d6a6a22.png)

You can try the [updated demo](https://pgiraud.github.io/ngeo/tree_indeterminate_3/examples/contribs/gmf/apps/desktop/).

**Comment by pgiraud** [comment]
> i think functions on layergroup and layers should appear on hover

We're not talking about all the functions, do we?
The idea of extra actions being available after a click on "cog" button is still OK, right? For example, the opacity slider should be kept in the menu in my opinion.

An important advantage of actions being in a menu is that we can have text along with the icon.
Also I'd prefer the layer tree doesn't become a christmas tree.  ;-)

What are the functions/actions that should necessarily be accessible in one-click, in your opinion?

**Comment by gnerred** [comment]
I have a problem with layers that are not visible on map and that are with a black text... I really don't know what is the best solution... what you think @rbovard and @svavoi ?

**Comment by rbovard** [comment]
I agree with @gnerred , black text for invisible layers is more confusing than your proposition. This is why we proposed that:
* Active and in range: black text
* Inactive and in range: grey text
* Active and not in range: grey text + icon (_which one?_)
* Inactive and not in range: grey text

For me, the most important is that if the layer is not visible in the map, the text is gray.

BTW, are you going to backport this logical to the mobile version to have a coherent behaviour?

PS: if other members of PSC would react on thisone it would be nice, since those specs are very important for the final users...

**Comment by svavoi** [comment]
> It's then difficult to know if a layer is active (selected) or not.

I agree with @gnerred and @rbovard. I think it will be more clear for the user if the layer is greyed out if not visible. But I also agree with @pgiraud that it is a little confusing when you select a layer and the layer stays grey. Maybe the italic option would be the best way to make it clear that there is something special about the layer.

I like the magnifier symbol more than the eye symbol because you can guess what the action will be when you click on it.

@pgiraud: I can not see any theme on the demo. Is there a log in I should use?

**Comment by rbovard** [comment]
> I can not see any theme on the demo. Is there a log in I should use?

Refresh the page, sometimes the themes aren't loaded...

**Comment by svavoi** [comment]
@rbovard: Thanks!

> What are the functions/actions that should necessarily be accessible in one-click, in your opinion?

For me the close button and the info button has to be accessible in one-click. For the others I agree with keeping them in the menu.

**Comment by pgiraud** [comment]
Here's what I propose:

**Out of Scale**

After some testing I can confirm that there's a confusion if the grey color is used both for "out of scale" and "inactive". I can demonstrate it with a prototype if you want.
Let's first start with italic + magnifier icon as a way to distinguish out of scale layers. If when it's coded and after some user testing the usability is still not appropriate, we can choose an other option.
Here's a video showing how it looks.
https://www.dropbox.com/s/4yukjv6itew1rkc/gmf2_out_of_scale_italic%20%281%29.mov?dl=0

**Actions**

"remove" and "info" action buttons are available on hover. Other actions/parameters are accessible within the menu.

**Comment by rbovard** [comment]
Ok, so let's go with the italic variant!

**Comment by gnerred** [comment]
Ok for me

**Comment by pgiraud** [comment]
I've updated the WIKI page.
I also added a block for legend.
Can you please give it a final review? Last comments expected before end of today. Thanks.

**Comment by gnerred** [comment]
Ok

**Comment by vvmalbre** [comment]
Some feedbacks from our side:
- For us, a directly accessible close-button is important as well, since we use "flush mode".
- The behaviour "black = active and visible", "black italic + magnifyer = out of range", "gray = inactive" is fine.
- We prefer "popover"
- Wouldn't it be better not to show anything when there's no legend icon defined (instead of the tick)? When you show the tick it's not very clear anymore what's a tick and what's a legend symbol.

We've got a proposition concerning the actions:
- Why not open the menu with the functionalities automatically when you remain more then f.e. 1s over a layer? Then you save a click and the user gets easy access to the legend, transparency, metainfo and time slider. When he has chosen what he want's to do the menu closes automatically again. Something like in the image below:
![example_functions_gmf21](https://cloud.githubusercontent.com/assets/3703270/14204047/c8f8135e-f801-11e5-86e6-019b39fe2f45.png)

**Comment by svavoi** [comment]
> Wouldn't it be better not to show anything when there's no legend icon defined (instead of the tick)? 

I like this proposition. + 1 @vvmalbre 

Some more remarks to the new specification:

- I don't like the "hide legend" link. Maybe we could have a symbol on hover that corresponds the sign for the layer groups? 
![legend](https://cloud.githubusercontent.com/assets/5998978/14207173/a5670ea6-f818-11e5-8d15-861851d906bd.png)


- In the specification the magnifier symbol is still in the menu. I think it is not necessary there anymore because it is now displayed next to the layer.
- It would be nice to have the layer name in a slightly bigger size than the legend text to have them stand out more.

Remark to the proposition concerning the actions from @vvmalbre:
- I see a problem with the time icon that should always be displayed next to the layer. I think I prefer to have them to the right. Like this, the action symbols don't affect all the other layertree items.

**Comment by vvmalbre** [comment]
@svavoi: Ok, thanks for your remarks. Just wondering: why is it important to have the time icon next to the layer? And: the trick with the menu that opens automatically could also be done using the "popover" proposition (hasn't necessarily to be done with a menu as it is in my image). This way, the action symbols wouldn't affect the layer tree.

**Comment by svavoi** [comment]
@vvmalbre: I think it is important to know which layer is a time layer without being over a layer with the mouse. If not you will not realize that there is something special about this layer.

**Comment by pgiraud** [comment]
Hi all,

It looks like we agree on most of the points written in the specs WIKI page. There are still some disagreements. And I'm afraid we are not going to agree easily without spending a lot of time.
Let's be more agile from now on.
What I propose is we go with how the specs are written currently. Then we do a lot of testing (with real users) and identify what the weaknesses of the design are. Then we'll go for a second round of specs.

**Comment by ybolognini** [comment]
@svavoi, @pgiraud juste removed the magnifier from the popup.

Now as @pgiraud said, I think we have to keep the specs as they are. I have the feeling that we agree on most points. Changing small things (like moving an icon from the layer line to the popup) should be possible after the first version.
