### ISSUE TITLE
Result in a window

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1773]
Spec https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231773-Result-in-a-window

**Comment by sbrunner** [comment]
Should reuse component done by #1800

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by mriedo** [comment]
Ok for me

**Comment by gnerred** [comment]
This is a relative important change with 1.6. In 1.6, all the results are visible in the popup window, the user only has to scroll down to see all the queried objects of all layers. We will certainly have problems with users that do not see that they have to click on arrows to see the other queried objects. What can be done to better show users that they can switch ? Color, hilight or twinkle the arrows or the numbers ?

**Comment by gsollberger** [comment]
+1 @gnerred

**Comment by vvmalbre** [comment]
For us it's fine. The filter is a very nice idea!

**Comment by rbovard** [comment]
Some remarks/questions:
* Are the results sorted (features and layers)?
* How the user can see that there is serveral layers of results?
* The filter is very nice, but how long is the choice kept (all session, until result window close)?
* I think it's logical but the attributes are translated?
* HTML tags can be used?

**Comment by ybolognini** [comment]
@gnerred @gsollberger What can be done to better show users that they can switch ? Color, hilight or twinkle the arrows or the numbers ?

We'll propose something to improve this. ping @pgiraud 

@rbovard Are the results sorted (features and layers)?

Results are grouped by layers. But as in version 1.6, there is no sorting (except if sorting is done in the mapfile)

@rbovard How the user can see that there is serveral layers of results?

By default all results are displayed. Then user can open filter and see all layers.

@rbovard The filter is very nice, but how long is the choice kept (all session, until result window close)?

I would say choice is reset at the end of session and when result window is closed. What do you think @pgiraud ?

@rbovard I think it's logical but the attributes are translated?

Name of attributes are translated (like in 1.6)

@rbovard HTML tags can be used?

HTML tags can be used (like in 1.6)

**Comment by ybolognini** [comment]
@gnerred @gsollberger What can be done to better show users that they can switch ? Color, hilight or twinkle the arrows or the numbers ?

We don't think it's a good idea to highlight the arrows because these aren't more important buttons than other buttons in the app. But yes, we could do something to incite the user to look for more results.

Maybe one solution would be to add text to the arrow, like we did for the "back" button on mobile. Something like "< Prev" and "Next >". And to gain some room, we could remove the "Result" before the numbers. 

--> @pgiraud will continue to think about it and maybe have another proposition.

@rbovard The filter is very nice, but how long is the choice kept (all session, until result window close)?

Actually this was mentioned in the specs: The filter settings are cleared when a new query is done.

**Comment by gnerred** [comment]
Okay for me that @pgiraud thinks about it and proposes something.

**Comment by rbovard** [comment]
> Actually this was mentioned in the specs: The filter settings are cleared when a new query is done.

Okay, didn't saw that at first reading

> Maybe one solution would be to add text to the arrow, like we did for the "back" button on mobile. Something like "< Prev" and "Next >". And to gain some room, we could remove the "Result" before the numbers.

Maybe a solution but make it translatable, so we can remove them with empty string.

**Comment by ybolognini** [comment]
@rbovard @gnerred @gsollberger 
@pgiraud changed the specs and added texts for buttons previous/next. I think it's much better now. @rbovard yes we could make this texts translatable.

**Comment by rbovard** [comment]
Okay for me, thanks.

**Comment by gnerred** [comment]
ok

**Comment by gsollberger** [comment]
okraye.
