### ISSUE TITLE
Map rotation behavior

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1861]
#### Update
Following PSC-dev meeting on January 15, 2016, map rotation must be deactivated. Rotation (with north button) and autorotation will be implemented later.

Issue for milestone 2.1 is here : https://github.com/camptocamp/c2cgeoportal/issues/1938

#### Question
What do we do about map rotation?  Now, map can be rotated but there is no button to put the north up again.

This question is also linked to the "compass" feature where the map is rotating when moving the smartphone. This feature was not in the requirements.

Do we simply disable the rotation feature (at least for now)?

**Comment by kalbermattenm** [comment]
Good question...

I think the first thing the GMF usergroup is going to ask, is why the map does rotated when using the compass...:

I think the following workflow would be reasonable:

* Desktop: currently, no rotation (or if yes, then a button on the map to rotate it to North again)
* Mobile: follow the user, use the geolocalilzation (add a rotate North button again).

I am going to ask the whole PSC about it... The complete framework is not yet completely clear for me...

But in the mean time, as it is out of the requirements, I do not really know what to do about it... Coming back to this issue as soon as I have more info...

@rbovard, what do you think about it ?

**Comment by sbrunner** [comment]
> Mobile: follow the user, use the geolocalilzation (add a rotate North button again).

An other possibility it that we don't add an other button, but we rotate to north when we disable the traking.

**Comment by rbovard** [comment]
### Rotation

> What do we do about map rotation? Now, map can be rotated but there is no button to put the north up again.

I think we should keep this core feature of OL3 on mobile and desktop, and add the North button like GeoAdmin does.

### Autorotation

For the "compass" feature, I'm not a big fan because:
* It's not very precise (just tested now and it was really wrong) and there is some noise when moving
* Not everyone want (and understand why) the map rotate when using geolocalilzation

But I can also see the need of some users (ie @gnerred), and the solution he talk about (using last position to set the direction and not the compass) is maybe one lead to avoid compass issues (precision, noise).

Maybe a solution is to add a paramater `autorotate` in geolocalilzation tool and the integrator can choose the behaviour he want?

**Comment by gnerred** [comment]
+1 @sbrunner (autorotate to north when tracking is disabled)
+1 @rbovard (autorotate parameter for the integrator)

**Comment by svarim** [comment]
+1 @sbrunner (autorotate to north when tracking is disabled)
+1 @rbovard (autorotate parameter for the integrator)
+1 Ruth (E-Mail): I think it would make sense to ask C2C how much effort/cost it means to implement “geolocalzation”. If it’s done quickly it could be done now, if it’s a big deal it should be done in Prio 2. For me it’s a good functionality but not the top priority.

**Comment by rbovard** [comment]
@ybolognini Am I wrong or the geolocation feature is already implemented? The question here is about autorotate, no?
