### ISSUE TITLE
Permalink UI

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2071]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232071-Permalink

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by gnerred** [comment]
Ok for me, looks good. Just remind that the backward compatibility with desktop 1.6 is necessary.

**Comment by mriedo** [comment]
Ok for me !

**Comment by gsollberger** [comment]
ok for me.

**Comment by vvmalbre** [comment]
Thanks for the specification. We've got the following remarks/questions:
- What about a multiserver area? Does the short-URL work there? If not, the integrator should be able to define, if the original URL or the short URL is used in the window.
- We don't see the need of placing the button in a different manner as the others. We would prefer to place it directly below the other buttons without space. The space looks a bit like a layout error.
- As for now, the window only opens when exactly clicking on the icon (the rest of the button doesn't react to the click). In FF45 and IE11 the window doesn't open at all (but this is maybe because it's still only a prototype).
- Would be good, if the URL would be marked when the window opens, so that a user can directly copy the link.

**Comment by svavoi** [comment]
Ok for me.
+1 @vvmalbre for placement of the button

**Comment by ybolognini** [comment]
@gnerred Just remind that the backward compatibility with desktop 1.6 is necessary

Yes, permalink is backward compatible

@vvmalbre What about a multiserver area? Does the short-URL work there?

Please @sbrunner could you check that?

@vvmalbre We don't see the need of placing the button in a different manner as the others

I think the position of the button wasn't final in the prototype. @pgiraud do you confirm? 

@vvmalbre As for now, the window only opens when exactly clicking on the icon [...]

Yes, this is just because it's a prototype

@vvmalbre Would be good, if the URL would be marked when the window opens, so that a user can directly copy the link

This should be possible

**Comment by rbovard** [comment]
Okay for me.

**Comment by ybolognini** [comment]
@rbovard is the redlining taken in account in permalink?

Yes it is. With the same limitation as in version 1.6 (too many redlining)

@vvmalbre What about a multiserver area? Does the short-URL work there?

Short-URLs, like editing, needs to have a single database or a way to synchronize multiple databases. At Camptocamp we are working on such solutions, but it is more an infrastructure problem than a GeoMapFish problem.

**Comment by rbovard** [comment]
Don't forget to add a message about too long url as it was in 1.6: https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/Permalink.js#L237-L240

By the way are you sure that is only related to IE, I have some case here with Chrome... In this case, it would be even better to not generate permalink if URL is too long. What do you think?

**Comment by ybolognini** [comment]
@rbovard Don't forget to add a message about too long url as it was in 1.6

--> @pgiraud could you add something about it in the specs (could be in the Architecture chapter)

@vvmalbre We don't see the need of placing the button in a different manner as the others

Actually there's a good reason. Other buttons are "tabs", they open a panel and they need to be seen as a group of tabs/tools. Permalink button launches a simple action (opening a window). @pgiraud will find a way to display this difference on UI more clearly.

@vvmalbre Would be good, if the URL would be marked when the window opens, so that a user can directly copy the link

Actually this is already mentioned in the specs.

@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

To all: except these two changes above, can we consider that specs are validated?

**Comment by gnerred** [comment]
Yes for me

**Comment by gsollberger** [comment]
ok for me.

**Comment by rbovard** [comment]
Okay for me.

About my remark for too long URL: we have some users that make to many redlining on the map, generate the permalink and copy it and when opening it, nothing appears. It would be better if the URL is too long, to avoid this situation, that no permalink is generated.

**Comment by svavoi** [comment]
ok for me.

**Comment by gnerred** [comment]
+1 @rbovard . In addition : it would be good if a message says to the user that the permalink is too long to be generated, and that a solution is to export the redlining in KML, to avoid loss of hours of drawing...

**Comment by rbovard** [comment]
+1 @gnerred, for that we can translate the warning message (it's what i'll do now in 1.6)

**Comment by vvmalbre** [comment]
Ok for me with two remarks/questions:
- Doesn't the length of a valid URL depend on the browser you use? So, what is "too long"?
- Will you offer the possibility for the integrator to decide if the short URL or the original URL is displayed?

**Comment by kalbermattenm** [comment]
The Canton of Jura just asked me an interesting question:

While it be possible to call external WMS layers with the permalink: if someone adds a federal WMS layer for instance using the future add WMS plugin, while this layer be kept in the permalink ?

@ybolognini, I do not have a single clue about the current behavior (v 1.6)... Do you know something about that ?

**Comment by rbovard** [comment]
> @vvmalbre Doesn't the length of a valid URL depend on the browser you use? So, what is "too long"?

In fact you can get server error with long long url: https://map.nyon.ch/s/8Kmv (error 414)

**Comment by rbovard** [comment]
> @kalbermattenm I do not have a single clue about the current behavior (v 1.6)... Do you know something about that ?

It returns a warning in 1.6 because app think that a layer is private: https://map.nyon.ch/s/Bt1T

On geoadmin, it works fine: https://s.geo.admin.ch/6c322b8709

**Comment by ybolognini** [comment]
@kalbermattenm @rbovard 
Permalink in 1.6 doesn't include WMS layers that were added by user. The warning message can be considered as a bug.

@vvmalbre @rbovard @gnerred 
About the maximum length, yes we can limit the size to 2083 (as seen here https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/Permalink.js#L237-L240) and display a message.
If it's ok for everyone @pgiraud will add a note in the specs.

@vvmalbre Will you offer the possibility for the integrator to decide if the short URL or the original URL is displayed?

We could do this, but is this option really needed? What would be the need of a non shortened URL?

To all @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm
Please comment ASAP if you have something to add

**Comment by kalbermattenm** [comment]
OK for us (@mriedo and myself)

@ybolognini, could you add the external layer addition stuff to the enhancement list ?

**Comment by rbovard** [comment]
Okay for me.

+1 @kalbermattenm

**Comment by gnerred** [comment]
@ybolognini you say "limit the size to 2083" : no, we have a lot of permalinks that contain more than 2083 characters. OK to display a warning message, but it is important to let generate a big permalink, that will be usable in browsers that support it.

**Comment by rbovard** [comment]
@gnerred There is also a server limit... https://map.cartoriviera.ch/s/wMiB

**Comment by ybolognini** [comment]
@gnerred This means the URL you generate today don't work on certain browsers?  Then OK, we can do it like this and display only a warning message.

**Comment by gnerred** [comment]
Yes that's it @ybolognini . @rbovard, the server limit is much longer than the browser limit. So is it possible to manage the server limit too, and in this case to avoid generation of permalink ? With a message like : "Permalink too long, please remove some drawings on the map" ?

**Comment by ybolognini** [comment]
@gnerred @rbovard 
Yes we can add a message when the server limit is exceeded, too.

**Comment by rbovard** [comment]
Perfect, thanks!
