### ISSUE TITLE
Problem with querying in somes cases

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2384]
In one of my themes, querying does not work : 

1°/ Go to theme "Infrastructures" https://preprod.cartoriviera.ch/v2/mobile/theme/infrastructures?lang=fr&baselayer_ref=plan_cadastral_201607&map_x=555378&map_y=144817&map_zoom=8

2°/ Try to query -> nothing is queried

**Comment by gnerred** [comment]
Neither in theme "Stationnement" and some others : 

https://preprod.cartoriviera.ch/v2/mobile/theme/signalisation_stationnement?lang=fr&baselayer_ref=plan_cadastral_201607&map_x=555378&map_y=144817&map_zoom=8

**Comment by fredj** [comment]
There is a javascript exception visible in the debug console.

Apparently, a layer named `wmts_plan_cadastral_201607` is configured in the application but is not present in the [WMTS capabilities file](https://preprod.cartoriviera.ch/tiles/1.0.0/WMTSCapabilities_preprod.xml)

(not sure it will resolve the query issue ...)

**Comment by sbrunner** [comment]
To be tested on 2.1?

**Comment by gnerred** [comment]
Still got problems with querying, to reproduce :

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/theme/infrastructures?baselayer_ref=plan_cadastral&lang=fr&map_x=554824&map_y=146439&map_zoom=9&tree_group_layers_default_mobile_group=tp_arret_bus%2Ctp_arret_train%2Ctp_ligne_bus%2Ctp_ligne_train&tree_groups=infrastructures%2Cinfrastructures_plans
2°/ Click on a red/blue line -> no result (it has to be queried and it works in 1.6)
3°/ Click on a white and blue point -> query OK

**Comment by gnerred** [comment]
It seems that layers that are in a group at mapserver level are concerned

**Comment by ger-benjamin** [comment]
To undertstand from where the problem come, I try your portal in debug mode (add a `debug` in the url (`https://preprod.cartoriviera.ch/v2/mobile/theme/infrastructures?debug&...`))

But the debug _mode_ doesn't work in your application. One problem come from here: https://preprod.cartoriviera.ch/v2/wsgi/closure-deps.js

The folder `cartoriviera/static-ngeo/components` doesn't exists. Can you add it manually (look at / copy : https://github.com/camptocamp/c2cgeoportal/tree/master/c2cgeoportal/scaffolds/create/%2Bpackage%2B/static-ngeo/components) ? Can you tell me if this folder is missing because a problem during the update processus or if that come from one of your manipulation ?

Thanks

**Comment by rbovard** [comment]
See https://github.com/camptocamp/c2cgeoportal/issues/2559#issuecomment-251968429 and @sbrunner answer...

**Comment by ger-benjamin** [comment]
Thanks @rbovard . Note that the two errors are not bound (during the make, it search for this folder 'components', and doesn't find one, but that doesn't cause any trouble.) It debug mode (mode only for developer purpose), this folder is require.

Note also that that was fixed. The folder is now create on update.

But you, you need to create manually it by doing:
```
cp -r CONST_create_template/<package>/static-ngeo/components <package>/static-ngeo
```

**Comment by gnerred** [comment]
OK, I have create this folder with your command, now debug mode is working on my mobile ngeo : 
https://preprod.cartoriviera.ch/v2/mobile/theme/infrastructures?debug

**Comment by ger-benjamin** [comment]
Thanks, I've tested the issue in our demo and I've created a bug in ngeo for that: https://github.com/camptocamp/ngeo/issues/1977

**Comment by sbrunner** [comment]
Thanks @ger-benjamin
