### ISSUE TITLE
GMF 2.0 seems not to take into account another OGC server adress

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2466]
I configured a OGC Server QGIS with it's server adress. The GetCapabilities is correctly loaded and the layers shown in the layer tree. But the layer is requested under /mapserv_proxy instead of /qgisserver, and logically mapserver returns the error `msWMSLoadGetMapParams(): WMS server error. Invalid layer(s) given in the LAYERS parameter. A layer might be disabled for this request. Check wms/ows_enable_request settings.`.

If I configure only qgis server (by replacing mapserver, as documented here https://camptocamp.github.io/c2cgeoportal/master/integrator/backend_qgis.html#apache-configuration, the QGIS layers work. But I want to use Mapserver and QGIS server in parallel, and not replace Mapserver.

**Comment by eleu** [comment]
Same goes for external wms services as f.e. http://wms.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0 . The internal mapserver URL is requested instead.

**Comment by ger-benjamin** [comment]
If you get the same result with your last url, the problem come not from c2cgeoportal.

In our demo, we use the geo admin as well and it work without problem with our other mapserver layers. See: theme cadastre, there: https://geomapfish-demo.camptocamp.net/2.1/theme/Cadastre?baselayer_ref=map&lang=en&tree_groups=Cadastre

**Comment by eleu** [comment]
ok I will look at the configuration in that project.

**Comment by ger-benjamin** [comment]
You can show a example with mapserver internal layer, geo.admin layer and a qgis server layer here : https://gmf-test.sig.cloud.camptocamp.net/bge/theme/test_thm?baselayer_ref=blank&lang=en&map_x=647655&map_y=179555&map_zoom=2&tree_enable_ch.swisstopo.dreiecksvermaschung=true&tree_enable_default=true&tree_group_layers_test_grp=default&tree_group_layers_test_grp_external=default&tree_group_layers_test_grp_internal=osm&tree_groups=test_grp_external%2Ctest_grp_internal

But it's true, I got one error: `The layer 'default' (default) is not defined in WMS capabilities from 'Test qgis'` (and a warning because the layer use not the https protocol, so you can't see it).

**Comment by eleu** [comment]
Ok thanks.
with the hint from @gberaudo we found that having a "mixed" layer group works (= a layer group that has two different OGC sources). 

If the layer group is of a single OGC Server source, it will fall back to mapserv_proxy, which is not correct if the OGC Server is another then the default one.

Keeping this open for fixing, this is just a workaround note.

**Comment by sbrunner** [comment]
Than it's an ngeo issue...

**Comment by sbrunner** [comment]
Replaced by: https://github.com/camptocamp/ngeo/issues/1752
