### ISSUE TITLE
HTTPS errors incoming on newer Chrome versions for demo

### ISSUE THREAD

**Issue by ponceta** [camptocamp/c2cgeoportal#2877]
On Chrome 54.0.2840.99 m everything is fine, but on Chrome 57.0.2987.110 for example.

https://geomapfish-demo.camptocamp.net/2.1/ will fail to load.

Mozilla is fine. Chrome mobile 56.0.2924.87 on android 5.0.0 and android 6.0.1

**Comment by fredj** [comment]
This is caused by the HTTPS certificat on camptocamp.net; this certificat was issued by StartCom Ltd but Chrome (and soon firefox) stopped to trust this company (see https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html)

We are currently replacing this certificate, it should be done in the next few days.

**Comment by ponceta** [comment]
Ok, fine, thank you for the quick answer! :) I close this since it doesn't concern the geomapfish project directly.
