### ISSUE TITLE
Access to secured WMS layers does not work from external client 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2921]
Version 2.1.2

I'm trying to access GMF WMS secured layers from an external client (QGIS for example) and it doesn't work. Only public layers are visible. 

Capabilities : https://preprod.cartoriviera.ch/preprod/wsgi/mapserv_proxy?SERVICE=WMS&REQUEST=GetCapabilities 

I tried 
curl gnerred:XXXX "https://preprod.cartoriviera.ch/preprod/wsgi/mapserv_proxy?SERVICE=WMS&REQUEST=GetCapabilities"

But I get the same result.

**Comment by gnerred** [comment]
I have a check of referer on these URLs, please tell me if I have to add some IP range.

**Comment by gnerred** [comment]
FYI : the getCapabilities of Yverdon, for example, returns all layers, even the secured ones, but they cannot be displayed via a getMap.

**Comment by rbovard** [comment]
> FYI : the getCapabilities of Yverdon, for example, returns all layers, even the secured ones, but they cannot be displayed via a getMap.

And Nyon?

**Comment by gnerred** [comment]
Not testable from here, because Nyon has defined a referer check like Cartoriviera (forbidden). But @rbovard you can test and answer yourself your question ;-)

**Comment by rbovard** [comment]
Thanks, it was just to be sure that it's still working since you were making tests ;)

**Comment by rbovard** [comment]
BTW maybe it's related to #2897?

**Comment by rbovard** [comment]
I just checked on my `2.1.4` and it's a little different:
* Without login
  * Private layers are in GetCapabilities --> **WRONG**
  * I can add them in QGIS and only the legend is displayed (no data) --> The legend should be protected no?
* With login
  * Private layers are shown in GetCapabilities --> **OK**
  * I can add them in QGIS and the data and the legend are displayed --> **OK**

On my `1.6.8` it's fine:
* Without login
  * Private layers are not in GetCapabilities --> **OK**
* With login
  * Private layers are in GetCapabilities --> **OK**
  * I can add them in QGIS and the data and the legend are displayed --> **OK**

So if I resume:
* There is a regression in `2.1.x` because private layers are in GetCapabilities --> Shoud be fixed in *c2cgeoportal*
* @gnerred You probably have another issue since private layers are not in your GetCapabilites (even connected) --> Did you check on an old `1.6.x`?

**Comment by gnerred** [comment]
Thanks @rbovard for your tests. Yes the behaviour is different on my 2.1.2 like you explain, but I would be happy to have the same behaviour as your 2.1.4, even if there is a little regression. Do you have defined restriction areas ? I have not here. I have no 1.6 more.

**Comment by gnerred** [comment]
I will test soon with 2.1.4, I hope I will then be in the same situation as you @rbovard

**Comment by rbovard** [comment]
I have some area resticted layers but in minority, I don't think it's related. Let's wait your tests with `2.1.4`

I'll open another issue for the regression to make things clearer for the tracking.

**Comment by gnerred** [comment]
I tested remote access from QGIS to WMS of Cartoriviera, and now it works, I can add a password and see data of secured layers. So problem solved, I close.
